//
// Generated file, do not edit! Created by nedtool 5.4 from messages/FloodingMessage.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __FLOODINGMESSAGE_M_H
#define __FLOODINGMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
	#include "veins/modules/messages/DemoSafetyMessage_m.h"
	#include "veins/base/utils/Coord.h"
// }}

/**
 * Class generated from <tt>messages/FloodingMessage.msg:22</tt> by nedtool.
 * <pre>
 * packet FloodingMessage extends Veins::DemoSafetyMessage
 * {
 *     Veins::Coord originPosition;
 *     int hopCount = 0;
 * }
 * </pre>
 */
class FloodingMessage : public ::Veins::DemoSafetyMessage
{
  protected:
    Veins::Coord originPosition;
    int hopCount;

  private:
    void copy(const FloodingMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const FloodingMessage&);

  public:
    FloodingMessage(const char *name=nullptr, short kind=0);
    FloodingMessage(const FloodingMessage& other);
    virtual ~FloodingMessage();
    FloodingMessage& operator=(const FloodingMessage& other);
    virtual FloodingMessage *dup() const override {return new FloodingMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual Veins::Coord& getOriginPosition();
    virtual const Veins::Coord& getOriginPosition() const {return const_cast<FloodingMessage*>(this)->getOriginPosition();}
    virtual void setOriginPosition(const Veins::Coord& originPosition);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FloodingMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FloodingMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __FLOODINGMESSAGE_M_H

